# .goreleaser.yaml
project_name: yt-dlp-console

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

builds:
  - id: default
    main: .
    binary: yt-dlp-console
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X=github.com/QuickOrBeDead/yt-dlp-console/cmd.version={{.Version}}

checksum:
  algorithm: sha256

release:
  github:
    owner: QuickOrBeDead
    name: yt-dlp-console
  draft: false
  prerelease: auto
  name_template: "Release {{.Version}}"

changelog:
  skip: false
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^refactor:'