name: release

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip bump')"
    outputs:
      new_tag: ${{ steps.version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Release Suffix
        id: suffix
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "val=beta" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          PRERELEASE: ${{ github.ref != 'refs/heads/main' }}
          PRERELEASE_SUFFIX: ${{ steps.suffix.outputs.val }}

  release:
    needs: tag
    if: ${{ needs.tag.outputs.new_tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
